# Generated by Django 3.2.3 on 2021-08-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TS', '0004_auto_20210802_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='misdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market_Name', models.CharField(max_length=255)),
                ('Store_Name', models.CharField(max_length=225)),
                ('Store_uid', models.IntegerField()),
                ('totalcount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
